language: ruby
cache: bundler
sudo: false
rvm:
  - 2.2.4
addons:
  postgresql: '9.4'
services:
  - redis-server
env:
  global:
    - secure: QOnNDieI+NdqXYLxqaxjSBDYnmVnH40btrGKub/DAe7Q6xq0JKd7MUE828bwM+Q64UTD2umTGEZgeqXu3bt/pn8RbjRNv/dZLCC5vKogGgZ8YPGal8eUbmccYlYgLY640wHzZift0u3fMYYNCKtNWeL+05rRHdJgO5NBATWgFGHcPLplw8aoHMskcDWR9ZC5LqIjQq7W58a+Qx3xmtBlr3v8+MnBetUv4YL56qjZXi8YcgSs42vAb6YtvyTXTpxnJniacaFmx52xosuJR5wnel6ZZ6ZH5cODp9O5aLF9HYiPRYa2nrSM82khG5yWqO5fVFEhcvJG0uKgkbm/k8535wKSC9s6CBv89ULN3Mz4w8H2nymTkVTinStKrX0Zc8hhJBQOGQwXCJFxlAIQMYmuJiNbPF4Dd58gT+xU9EWkXvnVXhJtUrn39z9A30zAfrSH6s4e8+p9CMYGOUxq+Xmj+vfTCkDE9y2t2D6QYw/IFeTqKYHJMDPYVCp9USZUNx/PjsRpx2974C22Aun3QnYSxfGNnHMcMmadGRK5IuR/ewC+OGt3X8d6FgNlEU0Czi+ratUniEJgoM+qh5InbxCneo5KvHJcFijc3mAt8anRK+Mk2Uw8rS2RBcPR+ursQ7pzVvRED6vLAFe4a0olDInd3ijNt78iLBKzgMVQPLu9dhg=
  matrix:
    - TEST_SUITE='bundle exec rake spec'
    - TEST_SUITE='bundle exec rake teaspoon'
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database app_test;' -U postgres
script: bundle exec $TEST_SUITE
before_deploy: ./bin/precompile.sh
deploy:
  provider: s3
  access_key_id: AKIAJ5J4VFRHXERP33WQ
  secret_access_key:
    secure: CDs+uVWFgGWLi/4rfI7FQw9EOpTFU11onKxuB7PLCjR3Gi5MXD3GmFnvGWskUhUIRkfhogAF7Y1TkjYCiRA7jo9gQGcQRJdOXNs3vksL5KjgbfEk9t6fiuW3rwVq4IFCo3uYzvI2jANgHj7psAgIQ20hdfSSX7vnw4uxnNcuQLV+LtxzfYWC5XFAdCWvSpBw1QXHLvS05+TdpB+KP/AHKMO7NFgRc94ZuDklghb2bCZMpsgIZl8vBo9bENuNVscBNRhzyWVoc0OMoOvA3HOQXb3SbGq6sWwF8KHDPV41fIUK/+ZHg5niXO8xDMeiyxPlAr9AJitcZ6yBZbPI/cJpm0d7X44g0DZQaHtev5ANC+79kvIGFJEZZeHozlvO6KCj2S+XgJGHpNedyaruq972YsScoMrS9bEHswUP4MVvuAFH5jyiyHWb6Yxel10AqLR99tFhfqRmYuxjzEaa1pqjr41LmnZNjaaSM08qUcL78CinB5sQeKAEd4G28N7Z/HJTKMbNQRvitecBuJDYXC+vG/BA/ZS17pbZ2Eo4XRsF1AqWJnYltttOGIr9RWMSrPPVdzbS/Kn2ykNvK6LBO9Cd8xUY73BzxQZiqsoLs33umG6EaxRquBOJ2XD242/LVggr1lk651AyLig0JHn1EDDtSxluQV6VNMKMoXT3dLZr7qc=
  bucket: stronglifters
  local_dir: pkg
  skip_cleanup: true
  upload-dir: production
  acl: private
  on:
    repo: stronglifters/surface
    branch: master
after_deploy: ./bin/deploy.sh
